version: "3"

services:
  #######################################
  # TSDB: Prometheus
  #######################################
  prom:
    image: "prom/prometheus"
    restart: always
    ports:
      - "${PROM_PORT:-9090}:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  #######################################
  # Logging: Loki
  #######################################
  loki:
    image: "grafana/loki"
    restart: always
    ports:
      - "${LOKI_PORT:-3100}:3100"

  #######################################
  # Dashboarding: Grafana
  #######################################
  grafana:
    image: "grafana/grafana:latest"
    restart: always
    ports:
      - "${GRAFANA_PORT:-3000}:3000"

  #######################################
  # ZerØ Analytics
  #######################################
  za:
    image: "ncarlier/za"
    restart: always
    environment:
      - ZA_CONFIG=/etc/zero-analytics.toml
    ports:
      - "${ZA_PORT:-8080}:8080"
    volumes:
      - ./zero-analytics.toml:/etc/zero-analytics.toml

